/**
 * @file code-themes.ts
 * @description Inline Prism syntax themes (avoid deep ESM subpath imports)
 */

import React from 'react';

export const DARK_CODE_THEME: Record<string, React.CSSProperties> = {
  'code[class*="language-"]': {
    color: '#d4d4d4',
    background: 'transparent',
    fontFamily: "'Fira Code', Consolas, Monaco, monospace",
    fontSize: '12px',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.6',
    tabSize: 4,
  } as React.CSSProperties,
  'pre[class*="language-"]': {
    color: '#d4d4d4',
    background: 'rgba(0,0,0,0.3)',
    fontFamily: "'Fira Code', Consolas, Monaco, monospace",
    fontSize: '12px',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.6',
    tabSize: 4,
    padding: '1em',
    margin: '0',
    overflow: 'auto',
    borderRadius: '8px',
  } as React.CSSProperties,
  comment: { color: '#6a9955' },
  prolog: { color: '#6a9955' },
  doctype: { color: '#6a9955' },
  cdata: { color: '#6a9955' },
  punctuation: { color: '#d4d4d4' },
  property: { color: '#9cdcfe' },
  tag: { color: '#569cd6' },
  boolean: { color: '#569cd6' },
  number: { color: '#b5cea8' },
  constant: { color: '#9cdcfe' },
  symbol: { color: '#b5cea8' },
  deleted: { color: '#ce9178' },
  selector: { color: '#d7ba7d' },
  'attr-name': { color: '#9cdcfe' },
  string: { color: '#ce9178' },
  char: { color: '#ce9178' },
  builtin: { color: '#4ec9b0' },
  inserted: { color: '#b5cea8' },
  operator: { color: '#d4d4d4' },
  entity: { color: '#569cd6' },
  url: { color: '#9cdcfe' },
  atrule: { color: '#c586c0' },
  'attr-value': { color: '#ce9178' },
  keyword: { color: '#c586c0' },
  function: { color: '#dcdcaa' },
  'class-name': { color: '#4ec9b0' },
  regex: { color: '#d16969' },
  important: { color: '#569cd6', fontWeight: 'bold' },
  variable: { color: '#9cdcfe' },
};

export const LIGHT_CODE_THEME: Record<string, React.CSSProperties> = {
  'code[class*="language-"]': {
    color: '#000000',
    background: 'transparent',
    fontFamily: "'Fira Code', Consolas, Monaco, monospace",
    fontSize: '12px',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.6',
    tabSize: 4,
  } as React.CSSProperties,
  'pre[class*="language-"]': {
    color: '#000000',
    background: 'rgba(0,0,0,0.04)',
    fontFamily: "'Fira Code', Consolas, Monaco, monospace",
    fontSize: '12px',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.6',
    tabSize: 4,
    padding: '1em',
    margin: '0',
    overflow: 'auto',
    borderRadius: '8px',
  } as React.CSSProperties,
  comment: { color: '#008000' },
  prolog: { color: '#008000' },
  doctype: { color: '#008000' },
  cdata: { color: '#008000' },
  punctuation: { color: '#393a34' },
  property: { color: '#001080' },
  tag: { color: '#800000' },
  boolean: { color: '#0000ff' },
  number: { color: '#098658' },
  constant: { color: '#001080' },
  symbol: { color: '#098658' },
  deleted: { color: '#a31515' },
  selector: { color: '#800000' },
  'attr-name': { color: '#e50000' },
  string: { color: '#a31515' },
  char: { color: '#a31515' },
  builtin: { color: '#267f99' },
  inserted: { color: '#098658' },
  operator: { color: '#000000' },
  entity: { color: '#0000ff' },
  url: { color: '#001080' },
  atrule: { color: '#af00db' },
  'attr-value': { color: '#a31515' },
  keyword: { color: '#af00db' },
  function: { color: '#795e26' },
  'class-name': { color: '#267f99' },
  regex: { color: '#811f3f' },
  important: { color: '#0000ff', fontWeight: 'bold' },
  variable: { color: '#001080' },
};
